// go generate protoc internal/protos/exam.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: internal/protos/exam.proto

package exam

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exam_GetEmployeeByID_FullMethodName    = "/priority.exam.Exam/GetEmployeeByID"
	Exam_GetEmployeeList_FullMethodName    = "/priority.exam.Exam/GetEmployeeList"
	Exam_GetDepartmentByID_FullMethodName  = "/priority.exam.Exam/GetDepartmentByID"
	Exam_GetDepartmentList_FullMethodName  = "/priority.exam.Exam/GetDepartmentList"
	Exam_GetProjectByID_FullMethodName     = "/priority.exam.Exam/GetProjectByID"
	Exam_GetProjectList_FullMethodName     = "/priority.exam.Exam/GetProjectList"
	Exam_GetManagerProjects_FullMethodName = "/priority.exam.Exam/GetManagerProjects"
)

// ExamClient is the client API for Exam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExamClient interface {
	GetEmployeeByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Employee, error)
	GetEmployeeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Employees, error)
	GetDepartmentByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Department, error)
	GetDepartmentList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Departments, error)
	GetProjectByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Project, error)
	GetProjectList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Projects, error)
	GetManagerProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ManagerProjects], error)
}

type examClient struct {
	cc grpc.ClientConnInterface
}

func NewExamClient(cc grpc.ClientConnInterface) ExamClient {
	return &examClient{cc}
}

func (c *examClient) GetEmployeeByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Employee, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Employee)
	err := c.cc.Invoke(ctx, Exam_GetEmployeeByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetEmployeeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Employees, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Employees)
	err := c.cc.Invoke(ctx, Exam_GetEmployeeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetDepartmentByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Department, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Department)
	err := c.cc.Invoke(ctx, Exam_GetDepartmentByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetDepartmentList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Departments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Departments)
	err := c.cc.Invoke(ctx, Exam_GetDepartmentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetProjectByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, Exam_GetProjectByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetProjectList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Projects, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Projects)
	err := c.cc.Invoke(ctx, Exam_GetProjectList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetManagerProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ManagerProjects], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Exam_ServiceDesc.Streams[0], Exam_GetManagerProjects_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ManagerProjects]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Exam_GetManagerProjectsClient = grpc.ServerStreamingClient[ManagerProjects]

// ExamServer is the server API for Exam service.
// All implementations must embed UnimplementedExamServer
// for forward compatibility.
type ExamServer interface {
	GetEmployeeByID(context.Context, *ID) (*Employee, error)
	GetEmployeeList(context.Context, *Empty) (*Employees, error)
	GetDepartmentByID(context.Context, *ID) (*Department, error)
	GetDepartmentList(context.Context, *Empty) (*Departments, error)
	GetProjectByID(context.Context, *ID) (*Project, error)
	GetProjectList(context.Context, *Empty) (*Projects, error)
	GetManagerProjects(*Empty, grpc.ServerStreamingServer[ManagerProjects]) error
	mustEmbedUnimplementedExamServer()
}

// UnimplementedExamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamServer struct{}

func (UnimplementedExamServer) GetEmployeeByID(context.Context, *ID) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeByID not implemented")
}
func (UnimplementedExamServer) GetEmployeeList(context.Context, *Empty) (*Employees, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeList not implemented")
}
func (UnimplementedExamServer) GetDepartmentByID(context.Context, *ID) (*Department, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentByID not implemented")
}
func (UnimplementedExamServer) GetDepartmentList(context.Context, *Empty) (*Departments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartmentList not implemented")
}
func (UnimplementedExamServer) GetProjectByID(context.Context, *ID) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectByID not implemented")
}
func (UnimplementedExamServer) GetProjectList(context.Context, *Empty) (*Projects, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectList not implemented")
}
func (UnimplementedExamServer) GetManagerProjects(*Empty, grpc.ServerStreamingServer[ManagerProjects]) error {
	return status.Errorf(codes.Unimplemented, "method GetManagerProjects not implemented")
}
func (UnimplementedExamServer) mustEmbedUnimplementedExamServer() {}
func (UnimplementedExamServer) testEmbeddedByValue()              {}

// UnsafeExamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamServer will
// result in compilation errors.
type UnsafeExamServer interface {
	mustEmbedUnimplementedExamServer()
}

func RegisterExamServer(s grpc.ServiceRegistrar, srv ExamServer) {
	// If the following call pancis, it indicates UnimplementedExamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exam_ServiceDesc, srv)
}

func _Exam_GetEmployeeByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetEmployeeByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetEmployeeByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetEmployeeByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetEmployeeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetEmployeeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetEmployeeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetEmployeeList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetDepartmentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetDepartmentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetDepartmentByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetDepartmentByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetDepartmentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetDepartmentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetDepartmentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetDepartmentList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetProjectByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetProjectByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetProjectByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetProjectByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetProjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetProjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetProjectList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetProjectList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetManagerProjects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExamServer).GetManagerProjects(m, &grpc.GenericServerStream[Empty, ManagerProjects]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Exam_GetManagerProjectsServer = grpc.ServerStreamingServer[ManagerProjects]

// Exam_ServiceDesc is the grpc.ServiceDesc for Exam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "priority.exam.Exam",
	HandlerType: (*ExamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployeeByID",
			Handler:    _Exam_GetEmployeeByID_Handler,
		},
		{
			MethodName: "GetEmployeeList",
			Handler:    _Exam_GetEmployeeList_Handler,
		},
		{
			MethodName: "GetDepartmentByID",
			Handler:    _Exam_GetDepartmentByID_Handler,
		},
		{
			MethodName: "GetDepartmentList",
			Handler:    _Exam_GetDepartmentList_Handler,
		},
		{
			MethodName: "GetProjectByID",
			Handler:    _Exam_GetProjectByID_Handler,
		},
		{
			MethodName: "GetProjectList",
			Handler:    _Exam_GetProjectList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetManagerProjects",
			Handler:       _Exam_GetManagerProjects_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/protos/exam.proto",
}
